### ISSUE TITLE
Reopening matches in Challonge does not update the open matches for the Server Role

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/brackette#8]
Reopening matches in Challonge forces the user to run the "reset everyone" button to refresh the open matches. This can be annoying as then we have to setup all the servers and clients again. This is caused because we aren't always pinging Challonge for open matches and as we retrieve open matches from in memory. We only request Challonge again after we update a match. Perhaps we could could consider a "update open matches" button that will request Challonge and update the open matches. This would be another settings option for Server Role.

**Comment by dannyreg** [comment]
resolved by [#b2e4df](https://github.com/HappyZombies/brackette/commit/b2e4df)
