### ISSUE TITLE
Improve and update UI

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/brackette#9]
Currently the UI uses [Propeller](http://propeller.in/), which is a Fraemwork I use if I want to simply prototyp something. 

Moving forward, I am thinking that it be best if this app uses some type of (better) Front End Framework, I am looking into what to use and I am currently leaning towards React and perhaps using Materialize CSS

Since the site uses cookies (which I might change to local storage...), it be straightforward to use and we *probably* won't have to use Redux.

**Comment by dannyreg** [comment]
Decided to use React. Will rewrite the project in React. 

React will be the tool that I officially use. The current version we have (0.0.1b) is the prototype to show how the app would work (and it does work).

**Comment by dannyreg** [comment]
Making a lot of progress so far. Hopefully I'll be done by next week!
